services:
  rpc-server-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rpc1
    environment:
      - PORT=5000
    ports:
      - "5000:5000"

  rpc-server-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rpc2
    environment:
      - PORT=5001
    ports:
      - "5001:5001"
