services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd
    command:
      - etcd
      - --name=etcd1
      - --data-dir=/etcd-data
      - --advertise-client-urls=http://etcd:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-cluster-token=my-cluster
      - --initial-cluster-state=new
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd-data:/etcd-data

  rpc-server-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rpc1
    environment:
      - PORT=5000
      - INSTANCE_ID=rpc1
      - ETCD_ENDPOINTS=etcd:2379  # Uses Docker's internal DNS
    ports:
      - "5000:5000"
    depends_on:
      - etcd

  rpc-server-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rpc2
    environment:
      - PORT=5001
      - INSTANCE_ID=rpc2
      - ETCD_ENDPOINTS=etcd:2379
    ports:
      - "5001:5001"
    depends_on:
      - etcd

volumes:
  etcd-data: